"""
Weather Edge Strategy — 4-layer signal model
═════════════════════════════════════════════

Trades Kalshi daily weather threshold markets (e.g., "Will Dallas high
exceed 89°F today?") by exploiting the gap between official forecasts
and what the market has priced.

LAYER 1 — METAR Intraday (highest priority)
  If the observed temperature already confirms the outcome, override
  model_prob to near-certainty (0.97 YES or 0.03 NO).
  Only valid for same-day markets — temperatures can't be "un-done".

LAYER 2 — NWS normCDF Base Model
  P(YES) = normCDF((NWS_forecast − threshold) / σ)
  σ = 3.0°F before 11 AM ET (more morning uncertainty)
  σ = 2.0°F after 11 AM ET  (tighter as the day resolves)

LAYER 3 — Ensemble Consensus (GFS + ECMWF via Open-Meteo)
  All 3 models agree directionally → +10¢ edge boost
  GFS/ECMWF disagree with NWS → skip trade entirely

LAYER 4 — Calibration Bias
  Historical finding: YES markets priced 35–65¢ win only 4–21% of the
  time on Kalshi weather markets (far below implied probability).
  When buying NO in this range → +15¢ edge credit.

Entry:   |effective_edge| > 20¢  AND  volume ≥ 1,000 contracts
         Market not closing within 60 minutes

Pricing:
  Edge ≥ 40¢ → PASSIVE  : limit at mid-price  (maker, zero fee)
  Edge 20–40¢ → MIDWAY  : limit 2¢ inside ask (likely maker)
  Unfilled 30+ min → CHASE: re-evaluate, fill at ask if still valid
"""
import math
from dataclasses import dataclass, field
from datetime import date, datetime, timezone
from typing import Optional
from zoneinfo import ZoneInfo

import pandas as pd
from rich.console import Console

from strategies.base_strategy import BaseStrategy, TradeSignal, Signal
from data.weather_data import (
    SERIES_CONFIG, model_prob, get_calibrated_sigma,
    fetch_all_forecasts, fetch_metar_observations, fetch_ensemble_forecasts,
)

console = Console()
ET = ZoneInfo("America/New_York")

# ── Constants (match Taylor's trader.py exactly) ──────────────────────────────
MIN_EDGE           = 0.20   # 20¢ minimum edge to enter
EDGE_PASSIVE       = 0.40   # ≥ 40¢ → place at mid (passive maker)
MIN_VOLUME         = 1_000  # minimum 24-hour contracts
SIGMA_EARLY        = 3.0    # °F — before 11 AM ET
SIGMA_LATE         = 2.0    # °F — after 11 AM ET
CUTOFF_HOUR        = 11     # hour (ET) when σ tightens
SKIP_IF_CLOSE_MINS = 60     # skip markets closing within N minutes

METAR_CERTAIN      = 0.97   # near-certainty when METAR confirms outcome
METAR_CERTAIN_NO   = 0.03   # near-certainty when METAR rules it out

CALIB_BIAS_LO      = 0.35   # lower bound of bias range (kept for reference)
CALIB_BIAS_HI      = 0.65   # upper bound
CALIB_BIAS_EDGE    = 0.00   # VALIDATED 2026-03-29: YES wins 50.7% in 35–65¢ range
                             # (142 markets, 30 days) — market is well-calibrated here.
                             # Original "4–21% win rate" claim does not hold.
                             # Layer 4 disabled to remove phantom edge.

ENSEMBLE_BOOST        = 0.10   # edge boost when all 3 models within 10pp
ENSEMBLE_SOFT_BOOST   = 0.05   # half boost when all 3 models within 20pp
ENSEMBLE_AGREE_FULL   = 0.10   # max spread for full boost
ENSEMBLE_AGREE_SOFT   = 0.20   # max spread for half boost (above this → skip)

KELLY_FRACTION     = 0.25   # quarter-Kelly (conservative until 100+ trade history)
KELLY_MAX_CONTRACTS = 10    # hard cap per trade regardless of Kelly output


# ── Market info dataclass ─────────────────────────────────────────────────────

@dataclass
class WeatherMarket:
    """A single open Kalshi weather threshold market."""
    series:      str
    ticker:      str
    city:        str
    temp_type:   str          # "high" or "low"
    threshold:   float
    strike_type: str          # "greater" or "less"
    bid:         float        # YES bid price (0–1)
    ask:         float        # YES ask price (0–1)
    mid:         float        # (bid + ask) / 2
    volume:      float        # 24-hour volume
    event_date:  Optional[date]


@dataclass
class WeatherSignal:
    """A trade signal generated by the 4-layer model."""
    market:           WeatherMarket
    side:             str            # "yes" or "no"
    model_prob:       float          # model probability (after METAR override)
    raw_edge:         float          # model_prob - mid (before boosts)
    effective_edge:   float          # after ensemble + calibration boosts
    source:           str            # "NWS", "METAR↑", "METAR↓"
    yes_price_cents:  int            # limit order price in cents
    entry_mode:       str            # "PASSIVE", "MIDWAY"
    entry_cost:       float          # dollars at risk per contract
    chase_price_cents: int           # aggressive fallback price
    notes:            list = field(default_factory=list)


# ── Parse Kalshi market dict ──────────────────────────────────────────────────

def _parse_event_date(ticker: str) -> Optional[date]:
    """Extract date from a ticker like KXHIGHTLV-26MAR29-T89."""
    for seg in ticker.split("-"):
        if len(seg) == 7 and seg[:2].isdigit() and seg[5:7].isdigit():
            try:
                return datetime.strptime(
                    "20" + seg[0:2] + seg[2:5] + seg[5:7], "%Y%b%d"
                ).date()
            except ValueError:
                pass
    return None


def _parse_threshold(market: dict) -> float:
    val = float(market.get("floor_strike") or 0)
    if val == 0:
        last = market.get("ticker", "").split("-")[-1]
        if last.startswith("T"):
            try:
                val = float(last[1:])
            except ValueError:
                pass
    return val


def parse_open_market(series: str, m: dict) -> Optional[WeatherMarket]:
    """
    Convert a raw Kalshi market dict into a WeatherMarket.
    Returns None if the market fails any filter.
    """
    ticker   = m.get("ticker", "")
    last_seg = ticker.split("-")[-1]

    if not (last_seg.startswith("T") and last_seg[1:].replace(".", "").isdigit()):
        return None

    vol = float(m.get("volume_24h_fp", 0))
    if vol < MIN_VOLUME:
        return None

    bid_raw = m.get("yes_bid_dollars")
    ask_raw = m.get("yes_ask_dollars")
    if bid_raw is None or ask_raw is None:
        return None
    bid, ask = float(bid_raw), float(ask_raw)
    if bid <= 0 or ask >= 1.0 or ask <= bid:
        return None

    close_str = m.get("close_time") or m.get("expiration_time")
    if close_str:
        try:
            close_dt  = datetime.fromisoformat(close_str.replace("Z", "+00:00"))
            mins_left = (close_dt - datetime.now(timezone.utc)).total_seconds() / 60
            if mins_left < SKIP_IF_CLOSE_MINS:
                return None
        except Exception:
            pass

    cfg = SERIES_CONFIG.get(series, {})
    return WeatherMarket(
        series      = series,
        ticker      = ticker,
        city        = cfg.get("city", "Unknown"),
        temp_type   = cfg.get("temp_type", "high"),
        threshold   = _parse_threshold(m),
        strike_type = m.get("strike_type", "greater"),
        bid         = bid,
        ask         = ask,
        mid         = (bid + ask) / 2.0,
        volume      = vol,
        event_date  = _parse_event_date(ticker),
    )


# ── Limit price helpers ───────────────────────────────────────────────────────

def smart_limit_price(
    side: str, bid: float, ask: float, mid: float, edge: float
) -> tuple:
    """
    Returns (yes_price_cents, entry_mode).

    PASSIVE  edge ≥ 40¢ — limit at mid (zero maker fee, patient)
    MIDWAY   edge 20–40¢ — 2¢ inside ask (likely still maker)
    """
    abs_edge = abs(edge)
    if side == "yes":
        price = mid if abs_edge >= EDGE_PASSIVE else ask - 0.02
        price = max(mid, min(ask, price))
        mode  = "PASSIVE" if abs_edge >= EDGE_PASSIVE else "MIDWAY"
    else:
        no_ask = 1.0 - bid
        no_mid = 1.0 - mid
        no_price = no_mid if abs_edge >= EDGE_PASSIVE else no_ask - 0.02
        no_price = max(no_mid, min(no_ask, no_price))
        price = 1.0 - no_price
        mode  = "PASSIVE" if abs_edge >= EDGE_PASSIVE else "MIDWAY"

    return max(1, min(99, round(price * 100))), mode


def aggressive_limit_price(side: str, bid: float, ask: float) -> int:
    """Full ask/bid price — used when chasing a timed-out order."""
    if side == "yes":
        return max(1, min(99, round(ask * 100)))
    return max(1, min(99, round(bid * 100)))


# ── Signal evaluation ─────────────────────────────────────────────────────────

def current_sigma(series: str = "") -> float:
    """
    Return the sigma (°F) for the current time of day.

    If `series` is provided and sigma_lookup.json exists, returns the
    per-city calibrated sigma for this series and month.
    Falls back to SIGMA_EARLY / SIGMA_LATE constants if lookup is missing.
    """
    hour = datetime.now(ET).hour
    if series:
        return get_calibrated_sigma(series, hour)
    return SIGMA_LATE if hour >= CUTOFF_HOUR else SIGMA_EARLY


def evaluate_market(
    market: WeatherMarket,
    series_forecasts: dict,
    sigma: float,
    metar_obs: dict,
    ensemble: dict,
) -> Optional[WeatherSignal]:
    """
    Run the 4-layer model on a single market.
    Returns a WeatherSignal if |effective_edge| > MIN_EDGE, otherwise None.
    """
    ed = market.event_date
    if ed is None:
        return None

    forecasts = series_forecasts.get(market.series, {})
    if ed not in forecasts:
        return None

    high_f, low_f = forecasts[ed]
    forecast = high_f if market.temp_type == "high" else low_f
    if forecast is None:
        return None

    # ── Layer 2: NWS normCDF base model ──────────────────────────────────────
    # Use per-city calibrated sigma (from sigma_lookup.json) if available;
    # fall back to the passed-in `sigma` (original hardcoded defaults).
    now_hour        = datetime.now(ET).hour
    effective_sigma = get_calibrated_sigma(market.series, now_hour)
    prob   = model_prob(forecast, market.threshold, market.strike_type, effective_sigma)
    source = "NWS"
    notes  = []

    # ── Layer 1: METAR intraday override (same-day only) ─────────────────────
    if metar_obs and market.city in metar_obs and ed == date.today():
        obs = metar_obs[market.city]["obs_temp"]

        if market.temp_type == "high":
            if market.strike_type == "greater" and obs > market.threshold:
                prob, source = METAR_CERTAIN, "METAR↑"
                notes.append(f"obs={obs:.1f}°>{market.threshold:.0f}° ✓YES")
            elif market.strike_type == "less" and obs > market.threshold:
                prob, source = METAR_CERTAIN_NO, "METAR↑"
                notes.append(f"obs={obs:.1f}°>{market.threshold:.0f}° ✓NO")
        elif market.temp_type == "low":
            if market.strike_type == "less" and obs < market.threshold:
                prob, source = METAR_CERTAIN, "METAR↓"
                notes.append(f"obs={obs:.1f}°<{market.threshold:.0f}° ✓YES")
            elif market.strike_type == "greater" and obs < market.threshold:
                prob, source = METAR_CERTAIN_NO, "METAR↓"
                notes.append(f"obs={obs:.1f}°<{market.threshold:.0f}° ✓NO")

    raw_edge       = prob - market.mid
    effective_edge = raw_edge

    # ── Layer 3: Ensemble consensus (GFS + ECMWF) ────────────────────────────
    if ensemble and market.city in ensemble:
        ed_str   = ed.isoformat()
        day_data = ensemble[market.city].get(ed_str, {})
        fc_key   = "high" if market.temp_type == "high" else "low"
        gfs_fc   = day_data.get(f"gfs_{fc_key}")
        ecmwf_fc = day_data.get(f"ecmwf_{fc_key}")

        if gfs_fc is not None and ecmwf_fc is not None:
            gfs_prob   = model_prob(gfs_fc,   market.threshold, market.strike_type, effective_sigma)
            ecmwf_prob = model_prob(ecmwf_fc, market.threshold, market.strike_type, effective_sigma)

            # Max pairwise spread across all three model probabilities
            max_spread = max(
                abs(prob - gfs_prob),
                abs(prob - ecmwf_prob),
                abs(gfs_prob - ecmwf_prob),
            )

            if max_spread > ENSEMBLE_AGREE_SOFT:
                return None  # models too far apart — skip
            elif max_spread <= ENSEMBLE_AGREE_FULL:
                boost = ENSEMBLE_BOOST       # all within 10pp → full +10¢
                tag   = "ALL AGREE"
            else:
                boost = ENSEMBLE_SOFT_BOOST  # within 20pp → soft +5¢
                tag   = "SOFT AGREE"

            effective_edge += boost if effective_edge > 0 else -boost
            notes.append(
                f"GFS={gfs_fc:.0f}° ECMWF={ecmwf_fc:.0f}° "
                f"[{tag} +{boost*100:.0f}¢]"
            )

    # ── Layer 4: Calibration bias ─────────────────────────────────────────────
    if CALIB_BIAS_LO <= market.mid <= CALIB_BIAS_HI and effective_edge < 0:
        effective_edge -= CALIB_BIAS_EDGE
        notes.append(f"[CALIB BIAS +{CALIB_BIAS_EDGE*100:.0f}¢ NO edge]")

    if abs(effective_edge) < MIN_EDGE:
        return None

    side = "yes" if effective_edge > 0 else "no"
    yes_price_cents, entry_mode = smart_limit_price(
        side, market.bid, market.ask, market.mid, effective_edge
    )
    entry_cost = (yes_price_cents / 100) if side == "yes" else (100 - yes_price_cents) / 100
    entry_cost = max(0.01, min(0.99, entry_cost))

    return WeatherSignal(
        market            = market,
        side              = side,
        model_prob        = prob,
        raw_edge          = raw_edge,
        effective_edge    = effective_edge,
        source            = source,
        yes_price_cents   = yes_price_cents,
        entry_mode        = entry_mode,
        entry_cost        = entry_cost,
        chase_price_cents = aggressive_limit_price(side, market.bid, market.ask),
        notes             = notes,
    )


def evaluate_all_markets(
    markets: list,
    series_forecasts: dict,
    sigma: float,
    metar_obs: dict,
    ensemble: dict,
) -> list:
    """Evaluate all open markets, return WeatherSignals sorted by |edge| descending."""
    signals = []
    for m in markets:
        sig = evaluate_market(m, series_forecasts, sigma, metar_obs, ensemble)
        if sig:
            signals.append(sig)
    signals.sort(key=lambda s: abs(s.effective_edge), reverse=True)
    return signals


# ── Kelly Criterion position sizing ──────────────────────────────────────────

MAKER_FEE_RATE = 0.0175  # Kalshi maker fee = 7% × 25% discount


def kelly_contracts(
    model_prob: float,
    entry_cost: float,
    balance: float,
    max_contracts: int = KELLY_MAX_CONTRACTS,
    kelly_fraction: float = KELLY_FRACTION,
) -> int:
    """
    Quarter-Kelly position sizing for binary prediction markets.

    For a YES contract at price c, net win after maker fee:
        net_win = (1 - c) - 0.0175 * c * (1 - c)  = (1 - c)(1 - 0.0175c)
        f* = (p * net_win - (1 - p) * c) / net_win

    We use quarter-Kelly (0.25×) by default until we have 100+ trades of
    live history to validate calibration. Returns at least 1, at most max_contracts.
    """
    c = entry_cost
    if balance <= 0 or c <= 0 or c >= 1:
        return 1
    net_win = (1.0 - c) * (1.0 - MAKER_FEE_RATE * c)
    if net_win <= 0 or model_prob * net_win <= (1.0 - model_prob) * c:
        return 1
    full_kelly = (model_prob * net_win - (1.0 - model_prob) * c) / net_win
    dollar_bet = balance * full_kelly * kelly_fraction
    contracts  = max(1, min(max_contracts, int(dollar_bet / c)))
    return contracts


# ── BaseStrategy wrapper (backtest compatibility) ────────────────────────────

class WeatherEdgeStrategy(BaseStrategy):
    """
    Thin BaseStrategy wrapper so the 4-layer model plugs into the
    existing backtest engine. For the live scan loop, call
    evaluate_all_markets() directly instead.
    """

    def __init__(self, sigma: float = SIGMA_EARLY):
        self.sigma = sigma

    @property
    def name(self) -> str:
        return f"WeatherEdge(σ={self.sigma}°F, edge>{MIN_EDGE*100:.0f}¢)"

    def generate_signal(
        self,
        df: pd.DataFrame,
        ticker: str,
        current_yes_price: int,
        count: int = 1,
        series: str = "",
        series_forecasts: dict = None,
        metar_obs: dict = None,
        ensemble: dict = None,
        market_dict: dict = None,
        **kwargs,
    ) -> TradeSignal:
        if not series or not series_forecasts or market_dict is None:
            return TradeSignal(
                signal=Signal.HOLD, ticker=ticker,
                price=current_yes_price, count=count,
                confidence=0.0, reason="Missing weather context",
            )

        market = parse_open_market(series, market_dict)
        if market is None:
            return TradeSignal(
                signal=Signal.HOLD, ticker=ticker,
                price=current_yes_price, count=count,
                confidence=0.0, reason="Market did not pass filters",
            )

        sig = evaluate_market(
            market, series_forecasts, self.sigma,
            metar_obs or {}, ensemble or {},
        )
        if sig is None:
            return TradeSignal(
                signal=Signal.HOLD, ticker=ticker,
                price=current_yes_price, count=count,
                confidence=0.0, reason="No edge after 4-layer model",
            )

        action = Signal.BUY_YES if sig.side == "yes" else Signal.BUY_NO
        confidence = min(0.95, 0.5 + abs(sig.effective_edge) * 1.5)
        reason = (
            f"[{market.city} {market.temp_type.upper()}] "
            f"src={sig.source}  fcst={forecast:.0f}°  "
            f"model={sig.model_prob*100:.1f}%  mid={market.mid*100:.0f}¢  "
            f"edge={sig.effective_edge*100:+.1f}¢  [{sig.entry_mode}]"
            + (f"  {' '.join(sig.notes)}" if sig.notes else "")
        )

        return TradeSignal(
            signal=action, ticker=ticker,
            price=sig.yes_price_cents, count=count,
            confidence=confidence, reason=reason,
        )
